TARGET=tst

PZCL_KERNEL_DIRS =kernel.sc1
PZCL_KERNEL_DIRS+=kernel.sc1-64

CPPSRC =main.cpp
CPPSRC+=../common/pzclutil.cpp
LIBS=

vpath %.cpp ../common

include /opt/pzsdk.ver3.0/make/default_pzcl_host.mk
