
DEFAULT_MAKE=/opt/pzsdk.ver3.0/make/default_pzcl_host.mk
TARGET=pzcEventProfiling

PZCL_KERNEL_DIRS =kernel.sc1
PZCL_KERNEL_DIRS+=kernel.sc1-64

CPPSRC =main.cpp
CPPSRC+=../common/pzclutil.cpp

vpath %.cpp ../common

include $(DEFAULT_MAKE)

